### ISSUE TITLE
The reconstruction code

### ISSUE THREAD

**Issue by Sissi-lu** [Loping151/ForPlane#12]
Hi,

Thank you for your fabulous work. It's amazing to find out how fast the render speed is.

When I wanted to reconstruct the point cloud after the training, I encountered a mistake. It seems that there is something wrong in the file ./tools/generate_pointclouds.py. Could you please upgrade the reconstruction code?

Thanks in advance!

**Comment by Loping151** [comment]
Sorry for the late reply...I had too many emails these days. ~~Just now I was sleeping, I dreamed of this issue and woke up to find it true...~~

The reconstruction visualization was not done by me but I managed to find the code on the machine the last time someone asked for it.
I'd temporarily put the code here: https://download.loping151.com/files/uploaded/forplane_pc_recon.py
