### ISSUE TITLE
Visualization of Dynamic and Static Fields

### ISSUE THREAD

**Issue by Greatxcw** [Loping151/ForPlane#15]
Hello, thank you very much for your excellent work. While reading the Forplane paper, I noticed that you are able to visualize dynamic and static fields. The paper describes how to do this, but I tried modifying the code and found it didn't work. Could you please let me know how to adjust the code to achieve the visualization effect?

**Comment by Loping151** [comment]
I guess the original code for that would be tough to find...
As described in the paper, you would disable half of the 6 planes (just comment them out) and scale the rendered image into 0-1. If you do not scale, you might see something black.
Plz describe in which way it didn't work and I'll see if I can help u.

**Comment by Greatxcw** [comment]
Thanks for the reply, I would like to know how this is implemented in the code, Thank you!

**Comment by Greatxcw** [comment]
你好，就是想知道一下在代码中是如何实现的，看了描述不知道在代码中如何修改实现。 @Loping151

**Comment by Loping151** [comment]
我忘得差不多了。。。我重新看的代码。

插值的代码应该是https://github.com/Loping151/ForPlane/blob/623161277cd026e0807f0cdd6125e8d5af47f8dc/forplanes/models/lerplane_field.py#L53

然后grid的定义位于这里
https://github.com/Loping151/ForPlane/blob/623161277cd026e0807f0cdd6125e8d5af47f8dc/forplanes/models/lerplane_field.py#L26

由此，grid输出的[2,4,5]是带 $\tau$ 的动态部分而[0,1,3]是静态。在插值代码里面，根据ci跳过一半的特征，就可以实现动态静态分离。shape没有改变，其他的应该不需要改。

**Comment by Greatxcw** [comment]
好的，感谢回复，我尝试一下

**Comment by Greatxcw** [comment]
请问是这样改么？
`for scale_id, grid in enumerate(ms_grids[:num_levels]):
        interp_space = 1.
        multi_interp_space = []
        for ci, coo_comb in enumerate(coo_combs):
            # interpolate in plane
            # shape of grid[ci]: 1, out_dim, *reso
            if ci==0 or ci==1 or ci==3:
                feature_dim = grid[ci].shape[1]
                interp_out_plane = (
                    grid_sample_wrapper(grid[ci], pts[..., coo_comb], mode=mode)
                    .view(-1, feature_dim)
                )
                # compute product over planes
                interp_space = interp_space * interp_out_plane
                multi_interp_space.append(interp_space)`

**Comment by Greatxcw** [comment]
请问是这样改么：
![image](https://github.com/user-attachments/assets/a6665eee-7088-4948-a2ea-5611f7d6affc)

**Comment by Loping151** [comment]
我觉得是这样。之后scale一下output应该就行

**Comment by Greatxcw** [comment]
谢谢，我再尝试一下
