### ISSUE TITLE
Qualitative results

### ISSUE THREAD

**Issue by ericzzj1989** [Loping151/ForPlane#16]
Hello, thank you very much for your excellent work!

I’m interested in reproducing the qualitative results from this project. Could you please provide some guidance on how to run the relevant code or any specific steps to achieve this?

Thank you for your help!

**Comment by Loping151** [comment]
To me, it seems I merged the metric calculation into the training script here at that time: https://github.com/Loping151/ForPlane/blob/623161277cd026e0807f0cdd6125e8d5af47f8dc/forplanes/runners/video_trainer.py#L260
So you can see here how the metrics are calculated. 

I suppose I used this logfile to save the metrics, and I used a [collector](https://github.com/Loping151/ForPlane/blob/main/forplanes/collector.py) to collect them. But that was for mass experiments.
