### ISSUE TITLE
Missing module/file and typos

### ISSUE THREAD

**Issue by CarloGem** [Loping151/ForPlane#2]
When running the command for training ` PYTHONPATH='.' python lerplanes/main.py --config-path config.yaml ` It fails and reports the following error: 

```
Traceback (most recent call last):
  File "$PATH/ForPlane/lerplanes/main.py", line 16, in <module>
    from lerplanes.utils.create_rendering import (decompose_space_time,
 File "$PATH/ForPlane/lerplanes/utils/create_rendering.py", line 14, in <module>
    from lerplanes.runners.static_trainer import StaticTrainer
ModuleNotFoundError: No module named 'lerplanes.runners.static_trainer'
```

To the best of my knowledge, the required module is still not present in the available repository, which causes the command to fail without any available solutions. 

On a less critical note, in the "Setting up Python Environment" section of the README, please note that the following command:
`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch `
may fail if the 'torch' module is not already installed. To ensure a smoother installation process, consider adding the PyTorch official installation commands to your setup guide just before running the above line. While this might be assumed by some users, explicitly stating it in the setup guide would be beneficial to prevent potential issues.

Furthermore, please correct the following typo in the README:

Replace: `pip install -r requirments.txt` with `pip install -r requirements.txt`

Lastly, in the "Set Up Dataset" section, it would be helpful to provide instructions on where to save the dataset and whether any changes to folder structures are necessary.

Thank you and congratuliation for your work, I hope to be able to test it on my machine as soon as possible.

**Comment by Loping151** [comment]
Thank you for your corrections. I have rewritten some sections of the readme and updated the corresponding code. Some functions were not updated properly since we recently removed some obsolete modules. I have reviewed the issues you raised and am inquiring with the first author about them. Will fix it soon.
