### ISSUE TITLE
Fail to exatract meshes given a trained model

### ISSUE THREAD

**Issue by ysjue** [Loping151/ForPlane#8]
Hi, appreiciate this fantastic work! 
After training the models, I tried to extract a mesh from the predicted density fields (kind of like what EndoNeRF and EndoSURF did in their paper) using Marching Cubes. However, I noticed that the predicted density field has no 0-density (0-sigma) grid, which disables Marching Cubes to extract surfaces effectively. No matter how I tuned the threshold, I couldn't extract any meshes visually making sense. 
May I ask if these observations are normally expected and not caused by some bugs in my implementation? Does this issue happen because the authors sample the rays in an efficient manner so that density predictions in unoccupied space are insufficiently penalized? Thanks!

**Comment by Loping151** [comment]
We haven't tested extracting mesh yet, but we believe the density distribution is accurate because the Forplane is able to provide sufficiently accurate depth maps.
