### ISSUE TITLE
About average_poses function? 

### ISSUE THREAD

**Issue by xuyaojian123** [Loping151/ForPlane#9]
I've always had a doubt. Could you explain why normalize(np.cross(z, y_)) is not -x？The coordinate system of poses is "right up back". Looking forward your reply.
![image](https://github.com/Loping151/ForPlane/assets/51220835/bdb787d7-aad4-4337-ae72-8abb5f579e22)

**Comment by Loping151** [comment]
(首先，这个函数并没有被我们用到。。不过你似乎在kplane也问了。。
(抱歉晚回复，前几天在考试。。
看的我一开始也很疑惑，但是
![image](https://github.com/Loping151/ForPlane/assets/97866915/e6c10869-6fed-47cc-97f6-15d7df549bf2)
如果你认为他的字母都是标在正方向上的，那似乎的确是左手系。

**Comment by xuyaojian123** [comment]
haha，谢谢你哈！

**Comment by xuyaojian123** [comment]
想请问下你的采样方式是用K-planes的proposal sample方法，还是NerfAcc工具包提供的采样呢？

**Comment by Loping151** [comment]
我写了个参数控制采样方法，不过不太直观（my bad
config中调整参数`occ_grid_reso`（`self.use_occ_grid = self.occ_grid_reso > 0`）控制使用proposal plane来sample还是nerfacc的occupancy grid

**Comment by xuyaojian123** [comment]
好的，谢谢。一般来说你是觉得nerfacc的occupancy grid的sample方法效果好点，还是proposal plane来sample的方法效果好点？

**Comment by Loping151** [comment]
**我认为**，就效果而言对于我们的任务差别并不显著，但是grid的方法的效果在于离散化了采样步骤，inference（即渲染速度）够快。对于一些更大的场景，比如尝试结合像zipnerf那样的工作，具体效果有待研究

**Comment by xuyaojian123** [comment]
好的，谢谢。能不能加个wx（[REDACTED]），我有几个mip-nerf论文的问题想请教你一下，周围没人可以请教的哈哈哈！！！
